### ISSUE TITLE
rip smart board

### ISSUE THREAD

**Issue by ghost** [SultanMu/cps731-lab1#9]
your intellect was not fully recognized

**Comment by hzhrn** [comment]
this issue should be escalated to top priority

**Comment by b2jeong** [comment]
I agree

**Comment by prdxTO** [comment]
He was so young

**Comment by ClarkYin** [comment]
![download](https://cloud.githubusercontent.com/assets/6474185/10079862/6e8685d6-62ba-11e5-8f5c-525ce0d67aa3.jpg)

**Comment by ClarkYin** [comment]
![download 1](https://cloud.githubusercontent.com/assets/6474185/10079877/7c01a42a-62ba-11e5-8641-a2d1ce6120b9.jpg)

**Comment by ClarkYin** [comment]
![download 2](https://cloud.githubusercontent.com/assets/6474185/10079883/863ff19e-62ba-11e5-9db2-a78eca9a195c.jpg)

**Comment by ClarkYin** [comment]
you must choose

**Comment by sankaL** [comment]
squirtle

**Comment by b2jeong** [comment]
yo what happened to squirtle

**Comment by ClarkYin** [comment]
naw....someone else do it

**Comment by prdxTO** [comment]
squirtle didnt make the cut?

**Comment by Sujeethan** [comment]
![](http://i.ytimg.com/vi/XzzQ6cFo5NM/hqdefault.jpg)

**Comment by b2jeong** [comment]
![download](https://cloud.githubusercontent.com/assets/14824772/10079942/d4eee1b0-62ba-11e5-8fa2-b37d31ad69d8.jpg)

**Comment by ghost** [comment]
![img_20150924_124752](https://cloud.githubusercontent.com/assets/3856006/10079971/0031ed68-62bb-11e5-88ea-061084c18deb.jpg)

i have the evidence they'll never get away with it now

**Comment by mhmmxx** [comment]
![2618670-0199714375-kappa](https://cloud.githubusercontent.com/assets/12279213/10079985/16a8cc42-62bb-11e5-9539-cac234461189.png)

**Comment by SultanMu** [comment]
Caught on Camera :)
